// Tetromino shapes and colors for Tetris game

export type TetrominoType = 'I' | 'O' | 'T' | 'S' | 'Z' | 'J' | 'L';

export interface TetrominoShape {
  shape: number[][];
  color: string;
}

// Tetromino shapes represented as 2D arrays (1 = filled, 0 = empty)
export const TETROMINOS: Record<TetrominoType, TetrominoShape> = {
  I: {
    shape: [
      [0, 0, 0, 0],
      [1, 1, 1, 1],
      [0, 0, 0, 0],
      [0, 0, 0, 0],
    ],
    color: 'bg-orange-500',
  },
  O: {
    shape: [
      [1, 1],
      [1, 1],
    ],
    color: 'bg-red-500',
  },
  T: {
    shape: [
      [0, 0, 0],
      [1, 1, 1],
      [0, 1, 0],
    ],
    color: 'bg-yellow-400',
  },
  S: {
    shape: [
      [0, 1, 1],
      [1, 1, 0],
      [0, 0, 0],
    ],
    color: 'bg-cyan-400',
  },
  Z: {
    shape: [
      [1, 1, 0],
      [0, 1, 1],
      [0, 0, 0],
    ],
    color: 'bg-green-500',
  },
  J: {
    shape: [
      [0, 0, 0],
      [1, 1, 1],
      [0, 0, 1],
    ],
    color: 'bg-pink-500',
  },
  L: {
    shape: [
      [0, 0, 0],
      [1, 1, 1],
      [1, 0, 0],
    ],
    color: 'bg-blue-500',
  },
};

// Tetromino type order for NES randomizer (TJZOSLI)
const TETROMINO_ORDER: TetrominoType[] = ['T', 'J', 'Z', 'O', 'S', 'L', 'I'];

// Last piece generated by NES randomizer (for tracking consecutive pieces)
let lastNESPieceIndex: number = -1;

// Get random tetromino type using NES-style randomizer
// This reduces the chance of getting the same piece twice in a row
// First roll: 0-7, if 0-6 and ≠ last piece → accept
// If 7 or same as last → re-roll 0-6 (guaranteed)
export function getRandomTetromino(): TetrominoType {
  // First roll: generate random number between 0 and 7
  const firstRoll = Math.floor(Math.random() * 8);
  
  let pieceIndex: number;
  
  if (firstRoll >= 0 && firstRoll <= 6 && firstRoll !== lastNESPieceIndex) {
    // Accept the first roll (not 7 and not same as last piece)
    pieceIndex = firstRoll;
  } else {
    // Re-roll: generate random number between 0 and 6 (guaranteed acceptance)
    pieceIndex = Math.floor(Math.random() * 7);
  }
  
  // Update last piece index
  lastNESPieceIndex = pieceIndex;
  
  return TETROMINO_ORDER[pieceIndex];
}

// Reset the NES randomizer state (call at game start)
export function resetNESRandomizer(): void {
  lastNESPieceIndex = -1;
}

// Rotate a shape 90 degrees clockwise
export function rotateShape(shape: number[][]): number[][] {
  const rows = shape.length;
  const cols = shape[0].length;
  const rotated: number[][] = [];
  
  for (let col = 0; col < cols; col++) {
    rotated[col] = [];
    for (let row = rows - 1; row >= 0; row--) {
      rotated[col][rows - 1 - row] = shape[row][col];
    }
  }
  
  return rotated;
}